const ReuseComponends = () => {
  const numLoop = () => {
    let numPara = "";
    for (let i = 1; i <= 10; i++) {
      let ranNum = Math.floor(Math.random() * 100);
      numPara += `Num ${i} is ${ranNum} `;
    }
    return numPara;
  };

  return (
    <div style={{ "background-color": "#cafafa" }}>
      <h1>this is generated by loop and math method..</h1>
      {numLoop()}
      <br />
    </div>
  );
};

export default ReuseComponends;
