const ReuseComponends = () => {
  const numLoop = () => {
    let numPara = "";
    for (let i = 1; i <= 10; i++) {
      let ranNum = Math.floor(Math.random() * 100);
      numPara += (
        <>
          `Num ${i} is ${ranNum} <br /> `
        </>
      );
    }
    return numPara;
  };

  const arr = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9];

  return (
    <div style={{ "background-color": "#cafafa" }}>
      <h1>this is generated by loop and math method..</h1>
      {/* {arr.map((i) => {
        return (
          <>
            {i}
            <br />{" "}
          </>
        );
      })} */}
      {numLoop()}
      <br />
    </div>
  );
};

export default ReuseComponends;
